# https://docs.github.com/en/actions/learn-github-actions/contexts

name: "release"

on:
  push:
    tags:
      - "v*"

permissions: write-all

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download All Artifact
      uses: actions/download-artifact@v4
    
    - name: Create Release Draft and Upload Artifacts
      uses: softprops/action-gh-release@v1
      with:
        name: SignerServer V${{ env.VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
        body_path: CHANGELOG.md
        files: |
          SignerServer-windows-latest-x64.zip
          SignerServer-ubuntu-latest-x64.zip
          SignerServer-ubuntu-latest-arm64.zip
        draft: true
